# Custom Language File for Launcher Customizer

[ejs.app]
title = "Silly SMP Launcher"
transparent = true 
[ejs.landing]
mediaGitHubURL = "https://github.com/ethany6/SillySMP"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/xMYSw5NH"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO SILLY SMP"
welcomeDescription = "Here you will find every mod pack ready to hit and play and load in. If you need any help feel free to ping ethan in the discord"
welcomeDescCTA = "You are just a few clicks away from Silly SMP Launcher."
